const zona = 
[
    {
        "posicion": 1,
        "equipo": "Equipo 1",
        "puntos": 6,
        "partidosJugados": 3,
        "partidosGanados": 3,
        "partidosPerdidos": 0,
        "setGanados": 6,
        "setPerdidos": 1,
        "coeficienteSet": 6.000,
        "puntosAFavor": 158,
        "puntosEnContra": 125,
        "coeficientePuntos": 1.264,
    },
    {
        "posicion": 2,
        "equipo": "Equipo 2",
        "puntos": 5,
        "partidosJugados": 3,
        "partidosGanados": 2,
        "partidosPerdidos": 1,
        "setGanados": 5,
        "setPerdidos": 3,
        "coeficienteSet": 1.667,
        "puntosAFavor": 168,
        "puntosEnContra": 151,
        "coeficientePuntos": 1.113,
    },
    {
        "posicion": 3,
        "equipo": "Equipo 3",
        "puntos": 4,
        "partidosJugados": 3,
        "partidosGanados": 1,
        "partidosPerdidos": 2,
        "setGanados": 3,
        "setPerdidos": 5,
        "coeficienteSet": 0.600,
        "puntosAFavor": 145,
        "puntosEnContra": 167,
        "coeficientePuntos": 0.868,
    },
    {
        "posicion": 4,
        "equipo": "Equipo 4",
        "puntos": 3,
        "partidosJugados": 3,
        "partidosGanados": 0,
        "partidosPerdidos": 3,
        "setGanados": 1,
        "setPerdidos": 6,
        "coeficienteSet": 0.167,
        "puntosAFavor": 132,
        "puntosEnContra": 160,
        "coeficientePuntos": 0.825,
    }
]

/*const partido = {
    "partido": 1,
    "local": "Equipo 1",
    "visitante": "Equipo 2",
    "set1Local": 25,
    "set1Visitante": 15,
    "set2Local": 10,
    "set2Visitante": 25,
    "set3Local": 10,
    "set3Visitante": 15,
    "set4Local": null,
    "set4Visitante": null,
    "set5Local": null,
    "set5Visitante": null,
}*/

export default zona