version: '3.8'
services:
  sejama-webserver:
    container_name: sejama-webserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
    links:
      - sejama-mysql-db
    networks:
      - sejama-network

  sejama-mysql-db:
    container_name: sejama-mysql-db
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    restart: 'always'
    expose:
      - '3307'
    ports:
      - "3307:3307"
    volumes:
      - mydatavolume:/var/lib/mysql
    networks:
      - sejama-network

  sejama-phpmyadmin:
    container_name: sejama-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - sejama-mysql-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: sejama-mysql-db
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - sejama-network

volumes:
  mydatavolume:
networks:
  sejama-network:
    driver: bridge